# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_ids: ['i-dac5473b']
      
  tasks:

    - name: Provision a set of instances
      ec2:
         aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
         aws_secret_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
         instance_ids: '{{ instance_ids }}'
         key_name: seminarkey.pem
         group: launch-wizard-4
         region: us-east-1
         zone: us-east-1a
         instance_type: t2.micro
         image: ami-2051294a
         vpc_subnet_id: subnet-fe900f89
         wait: true
         count_tag:
            Name: Seminar
         instance_tags:
            Name: Seminar
      register: ec2
